language: python
python:
  - "2.7"
before_install:
  - "export DISPLAY=:99.0"         # Required for graphics
  - "sh -e /etc/init.d/xvfb start" # Required for graphics
install:
  - pip install pandas numpy matplotlib
  - pip install coveralls
before_script:
  - export PYTHONPATH="$PYTHONPATH:/home/travis/build/codles/UpDownMethods"
script:
  - coverage run -m unittest discover -s tests -v
after_success:
  - overalls
