language: python
python:
  - "2.7"
before_install:
  - "export DISPLAY=:99.0"         # Required for graphics
  - "sh -e /etc/init.d/xvfb start" # Required for graphics
install:
  - pip install pandas numpy matplotlib
before_script:
  - export PYTHONPATH="$PYTHONPATH:/home/travis/build/codles/UpDownMethods"
script:  
  - print $PYTHONPATH
  - pwd
  - ls -al
  - python tests/Levitt1971-Fig5.py
